-- Author
INSERT INTO public.authors VALUES (1, 'Sarah J. Maas', NULL, NULL);

-- Book Tags
INSERT INTO public.book_tags VALUES (1, 1);
INSERT INTO public.book_tags VALUES (1, 5);
INSERT INTO public.book_tags VALUES (1, 16);
INSERT INTO public.book_tags VALUES (1, 9);
INSERT INTO public.book_tags VALUES (1, 17);
INSERT INTO public.book_tags VALUES (1, 18);
INSERT INTO public.book_tags VALUES (1, 26);
INSERT INTO public.book_tags VALUES (1, 22);
INSERT INTO public.book_tags VALUES (1, 23);
INSERT INTO public.book_tags VALUES (1, 24);
INSERT INTO public.book_tags VALUES (1, 25);
INSERT INTO public.book_tags VALUES (1, 35);
INSERT INTO public.book_tags VALUES (1, 36);
INSERT INTO public.book_tags VALUES (1, 37);
INSERT INTO public.book_tags VALUES (1, 38);
INSERT INTO public.book_tags VALUES (1, 47);
INSERT INTO public.book_tags VALUES (1, 50);
INSERT INTO public.book_tags VALUES (1, 58);
INSERT INTO public.book_tags VALUES (1, 59);
INSERT INTO public.book_tags VALUES (2, 1);
INSERT INTO public.book_tags VALUES (2, 5);
INSERT INTO public.book_tags VALUES (2, 9);
INSERT INTO public.book_tags VALUES (2, 16);
INSERT INTO public.book_tags VALUES (2, 19);
INSERT INTO public.book_tags VALUES (2, 18);
INSERT INTO public.book_tags VALUES (2, 23);
INSERT INTO public.book_tags VALUES (2, 21);
INSERT INTO public.book_tags VALUES (2, 27);
INSERT INTO public.book_tags VALUES (2, 22);
INSERT INTO public.book_tags VALUES (2, 20);
INSERT INTO public.book_tags VALUES (2, 35);
INSERT INTO public.book_tags VALUES (2, 37);
INSERT INTO public.book_tags VALUES (2, 43);
INSERT INTO public.book_tags VALUES (2, 40);
INSERT INTO public.book_tags VALUES (2, 47);
INSERT INTO public.book_tags VALUES (2, 48);
INSERT INTO public.book_tags VALUES (2, 58);
INSERT INTO public.book_tags VALUES (2, 59);
INSERT INTO public.book_tags VALUES (3, 1);
INSERT INTO public.book_tags VALUES (3, 16);
INSERT INTO public.book_tags VALUES (3, 13);
INSERT INTO public.book_tags VALUES (3, 18);
INSERT INTO public.book_tags VALUES (3, 19);
INSERT INTO public.book_tags VALUES (3, 22);
INSERT INTO public.book_tags VALUES (3, 23);
INSERT INTO public.book_tags VALUES (3, 26);
INSERT INTO public.book_tags VALUES (3, 29);
INSERT INTO public.book_tags VALUES (3, 36);
INSERT INTO public.book_tags VALUES (3, 43);
INSERT INTO public.book_tags VALUES (3, 38);
INSERT INTO public.book_tags VALUES (3, 47);
INSERT INTO public.book_tags VALUES (3, 59);
INSERT INTO public.book_tags VALUES (3, 32);
INSERT INTO public.book_tags VALUES (3, 54);
INSERT INTO public.book_tags VALUES (4, 1);
INSERT INTO public.book_tags VALUES (4, 5);
INSERT INTO public.book_tags VALUES (4, 12);
INSERT INTO public.book_tags VALUES (4, 10);
INSERT INTO public.book_tags VALUES (4, 18);
INSERT INTO public.book_tags VALUES (4, 33);
INSERT INTO public.book_tags VALUES (4, 34);
INSERT INTO public.book_tags VALUES (4, 31);
INSERT INTO public.book_tags VALUES (4, 30);
INSERT INTO public.book_tags VALUES (4, 32);
INSERT INTO public.book_tags VALUES (4, 20);
INSERT INTO public.book_tags VALUES (4, 39);
INSERT INTO public.book_tags VALUES (4, 36);
INSERT INTO public.book_tags VALUES (4, 37);
INSERT INTO public.book_tags VALUES (4, 40);
INSERT INTO public.book_tags VALUES (4, 55);
INSERT INTO public.book_tags VALUES (4, 49);
INSERT INTO public.book_tags VALUES (4, 59);
INSERT INTO public.book_tags VALUES (4, 45);
INSERT INTO public.book_tags VALUES (5, 1);
INSERT INTO public.book_tags VALUES (5, 5);
INSERT INTO public.book_tags VALUES (5, 9);
INSERT INTO public.book_tags VALUES (5, 16);
INSERT INTO public.book_tags VALUES (5, 18);
INSERT INTO public.book_tags VALUES (5, 19);
INSERT INTO public.book_tags VALUES (5, 17);
INSERT INTO public.book_tags VALUES (5, 21);
INSERT INTO public.book_tags VALUES (5, 22);
INSERT INTO public.book_tags VALUES (5, 23);
INSERT INTO public.book_tags VALUES (5, 26);
INSERT INTO public.book_tags VALUES (5, 27);
INSERT INTO public.book_tags VALUES (5, 25);
INSERT INTO public.book_tags VALUES (5, 20);
INSERT INTO public.book_tags VALUES (5, 35);
INSERT INTO public.book_tags VALUES (5, 37);
INSERT INTO public.book_tags VALUES (5, 36);
INSERT INTO public.book_tags VALUES (5, 40);
INSERT INTO public.book_tags VALUES (5, 43);
INSERT INTO public.book_tags VALUES (5, 38);
INSERT INTO public.book_tags VALUES (5, 47);
INSERT INTO public.book_tags VALUES (5, 48);
INSERT INTO public.book_tags VALUES (5, 58);
INSERT INTO public.book_tags VALUES (5, 59);
INSERT INTO public.book_tags VALUES (5, 54);
INSERT INTO public.book_tags VALUES (5, 50);
INSERT INTO public.book_tags VALUES (5, 52);
INSERT INTO public.book_tags VALUES (6, 1);
INSERT INTO public.book_tags VALUES (6, 5);
INSERT INTO public.book_tags VALUES (6, 3);
INSERT INTO public.book_tags VALUES (6, 9);
INSERT INTO public.book_tags VALUES (6, 16);
INSERT INTO public.book_tags VALUES (6, 12);
INSERT INTO public.book_tags VALUES (6, 20);
INSERT INTO public.book_tags VALUES (6, 27);
INSERT INTO public.book_tags VALUES (6, 22);
INSERT INTO public.book_tags VALUES (6, 23);
INSERT INTO public.book_tags VALUES (6, 26);
INSERT INTO public.book_tags VALUES (6, 17);
INSERT INTO public.book_tags VALUES (6, 18);
INSERT INTO public.book_tags VALUES (6, 30);
INSERT INTO public.book_tags VALUES (6, 31);
INSERT INTO public.book_tags VALUES (6, 24);
INSERT INTO public.book_tags VALUES (6, 28);
INSERT INTO public.book_tags VALUES (6, 21);
INSERT INTO public.book_tags VALUES (6, 37);
INSERT INTO public.book_tags VALUES (6, 36);
INSERT INTO public.book_tags VALUES (6, 35);
INSERT INTO public.book_tags VALUES (6, 40);
INSERT INTO public.book_tags VALUES (6, 39);
INSERT INTO public.book_tags VALUES (6, 43);
INSERT INTO public.book_tags VALUES (6, 38);
INSERT INTO public.book_tags VALUES (6, 52);
INSERT INTO public.book_tags VALUES (6, 53);
INSERT INTO public.book_tags VALUES (6, 49);
INSERT INTO public.book_tags VALUES (6, 45);
INSERT INTO public.book_tags VALUES (6, 58);
INSERT INTO public.book_tags VALUES (6, 59);
INSERT INTO public.book_tags VALUES (6, 57);
INSERT INTO public.book_tags VALUES (7, 1);
INSERT INTO public.book_tags VALUES (7, 5);
INSERT INTO public.book_tags VALUES (7, 9);
INSERT INTO public.book_tags VALUES (7, 16);
INSERT INTO public.book_tags VALUES (7, 15);
INSERT INTO public.book_tags VALUES (7, 18);
INSERT INTO public.book_tags VALUES (7, 33);
INSERT INTO public.book_tags VALUES (7, 34);
INSERT INTO public.book_tags VALUES (7, 17);
INSERT INTO public.book_tags VALUES (7, 32);
INSERT INTO public.book_tags VALUES (7, 22);
INSERT INTO public.book_tags VALUES (7, 25);
INSERT INTO public.book_tags VALUES (7, 27);
INSERT INTO public.book_tags VALUES (7, 20);
INSERT INTO public.book_tags VALUES (7, 19);
INSERT INTO public.book_tags VALUES (7, 36);
INSERT INTO public.book_tags VALUES (7, 38);
INSERT INTO public.book_tags VALUES (7, 42);
INSERT INTO public.book_tags VALUES (7, 40);
INSERT INTO public.book_tags VALUES (7, 37);
INSERT INTO public.book_tags VALUES (7, 35);
INSERT INTO public.book_tags VALUES (7, 49);
INSERT INTO public.book_tags VALUES (7, 59);
INSERT INTO public.book_tags VALUES (7, 50);
INSERT INTO public.book_tags VALUES (7, 53);
INSERT INTO public.book_tags VALUES (7, 58);
INSERT INTO public.book_tags VALUES (7, 55);
INSERT INTO public.book_tags VALUES (8, 1);
INSERT INTO public.book_tags VALUES (8, 5);
INSERT INTO public.book_tags VALUES (8, 3);
INSERT INTO public.book_tags VALUES (8, 9);
INSERT INTO public.book_tags VALUES (8, 16);
INSERT INTO public.book_tags VALUES (8, 12);
INSERT INTO public.book_tags VALUES (8, 18);
INSERT INTO public.book_tags VALUES (8, 19);
INSERT INTO public.book_tags VALUES (8, 26);
INSERT INTO public.book_tags VALUES (8, 20);
INSERT INTO public.book_tags VALUES (8, 17);
INSERT INTO public.book_tags VALUES (8, 22);
INSERT INTO public.book_tags VALUES (8, 23);
INSERT INTO public.book_tags VALUES (8, 24);
INSERT INTO public.book_tags VALUES (8, 25);
INSERT INTO public.book_tags VALUES (8, 30);
INSERT INTO public.book_tags VALUES (8, 31);
INSERT INTO public.book_tags VALUES (8, 21);
INSERT INTO public.book_tags VALUES (8, 27);
INSERT INTO public.book_tags VALUES (8, 33);
INSERT INTO public.book_tags VALUES (8, 34);
INSERT INTO public.book_tags VALUES (8, 35);
INSERT INTO public.book_tags VALUES (8, 37);
INSERT INTO public.book_tags VALUES (8, 36);
INSERT INTO public.book_tags VALUES (8, 43);
INSERT INTO public.book_tags VALUES (8, 39);
INSERT INTO public.book_tags VALUES (8, 40);
INSERT INTO public.book_tags VALUES (8, 38);
INSERT INTO public.book_tags VALUES (8, 45);
INSERT INTO public.book_tags VALUES (8, 59);
INSERT INTO public.book_tags VALUES (8, 49);
INSERT INTO public.book_tags VALUES (8, 52);
INSERT INTO public.book_tags VALUES (8, 53);
INSERT INTO public.book_tags VALUES (8, 58);
INSERT INTO public.book_tags VALUES (8, 57);

-- Books
INSERT INTO public.books VALUES (1, 'Throne of Glass', NULL, 1, 2012, 'An assassin is pulled from imprisonment to compete for a chance at freedom, uncovering court intrigue, dark magic, and dangerous secrets along the way.', 406, 'Throne of Glass', 1, '9781639730940', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1673566495i/76703559.jpg', 1);
INSERT INTO public.books VALUES (2, 'Crown of Midnight', NULL, 1, 2013, 'Celaena’s new role as the king’s assassin forces her into deadly choices, unraveling conspiracies, forbidden loyalties, and a truth that threatens everything she thought she knew.', 432, 'Throne of Glass', 2, '9781619630628', NULL, 1);
INSERT INTO public.books VALUES (3, 'The Assassin''s Blade', NULL, 1, 2014, 'A collection of prequel novellas following Celaena Sardothien’s early missions, betrayals, and the events that shape her into the assassin she becomes.', 448, 'Throne of Glass', 0, '9781619633612', NULL, 1);
INSERT INTO public.books VALUES (4, 'Heir of Fire', NULL, 1, 2014, 'Sent across the sea to confront her past, Celaena faces brutal training, ancient magic, and a rising darkness that forces her to choose who she will become.', 576, 'Throne of Glass', 3, '9781619630659', NULL, 1);
INSERT INTO public.books VALUES (5, 'Queen of Shadows', NULL, 1, 2015, 'Aelin Galathynius returns to confront her past, rescue her friends, and reclaim her kingdom. As political intrigue deepens and old enemies rise, she must embrace her identity and power to survive the shadows closing in.', 648, 'Throne of Glass', 4, '9781619636040', NULL, 1);
INSERT INTO public.books VALUES (6, 'Empire of Storms', NULL, 1, 2016, 'Aelin’s allies are scattered and ancient forces awaken as war sweeps across Erilea. Political alliances, betrayals, and mythic powers collide as she races to protect her world from destruction.', 720, 'Throne of Glass', 5, '9781619636071', NULL, 1);
INSERT INTO public.books VALUES (7, 'Tower of Dawn', NULL, 1, 2017, 'Chaol Westfall journeys to the Southern Continent seeking healing and political alliance. What begins as diplomacy becomes a profound exploration of trauma, recovery, identity, and unexpected connection.', 688, 'Throne of Glass', 6, '9781619636101', NULL, 1);
INSERT INTO public.books VALUES (8, 'Kingdom of Ash', NULL, 1, 2018, 'The final battle for Erilea erupts as Aelin endures captivity, armies clash, and ancient powers rise. Sacrifice, destiny, and devastating choices shape the mythic conclusion to the series.', 992, 'Throne of Glass', 7, '9781619636101', NULL, 1);

-- Series
INSERT INTO public.series VALUES (1, 'Throne of Glass');

-- Tags
INSERT INTO public.tags VALUES (1, 'fantasy', 'genre');
INSERT INTO public.tags VALUES (2, 'dark fantasy', 'genre');
INSERT INTO public.tags VALUES (3, 'epic fantasy', 'genre');
INSERT INTO public.tags VALUES (4, 'urban fantasy', 'genre');
INSERT INTO public.tags VALUES (5, 'high fantasy', 'genre');
INSERT INTO public.tags VALUES (6, 'low fantasy', 'genre');
INSERT INTO public.tags VALUES (7, 'romantic fantasy', 'genre');
INSERT INTO public.tags VALUES (8, 'grimdark', 'genre');
INSERT INTO public.tags VALUES (9, 'political fantasy', 'subgenre');
INSERT INTO public.tags VALUES (10, 'magical academy', 'subgenre');
INSERT INTO public.tags VALUES (11, 'portal fantasy', 'subgenre');
INSERT INTO public.tags VALUES (12, 'mythic fantasy', 'subgenre');
INSERT INTO public.tags VALUES (13, 'sword and sorcery', 'subgenre');
INSERT INTO public.tags VALUES (14, 'fae fantasy', 'subgenre');
INSERT INTO public.tags VALUES (15, 'historical fantasy', 'subgenre');
INSERT INTO public.tags VALUES (16, 'adventure fantasy', 'subgenre');
INSERT INTO public.tags VALUES (17, 'identity', 'theme');
INSERT INTO public.tags VALUES (18, 'trauma', 'theme');
INSERT INTO public.tags VALUES (19, 'grief', 'theme');
INSERT INTO public.tags VALUES (20, 'destiny vs choice', 'theme');
INSERT INTO public.tags VALUES (21, 'rebellion', 'theme');
INSERT INTO public.tags VALUES (22, 'loyalty', 'theme');
INSERT INTO public.tags VALUES (23, 'betrayal', 'theme');
INSERT INTO public.tags VALUES (24, 'found family', 'theme');
INSERT INTO public.tags VALUES (25, 'redemption', 'theme');
INSERT INTO public.tags VALUES (26, 'survival', 'theme');
INSERT INTO public.tags VALUES (27, 'power and corruption', 'theme');
INSERT INTO public.tags VALUES (28, 'forbidden love', 'theme');
INSERT INTO public.tags VALUES (29, 'coming of age', 'theme');
INSERT INTO public.tags VALUES (30, 'ancient powers', 'theme');
INSERT INTO public.tags VALUES (31, 'magic awakening', 'theme');
INSERT INTO public.tags VALUES (32, 'mentorship', 'theme');
INSERT INTO public.tags VALUES (33, 'healing', 'theme');
INSERT INTO public.tags VALUES (34, 'self-discovery', 'theme');
INSERT INTO public.tags VALUES (35, 'dark', 'tone');
INSERT INTO public.tags VALUES (36, 'emotional', 'tone');
INSERT INTO public.tags VALUES (37, 'intense', 'tone');
INSERT INTO public.tags VALUES (38, 'character-driven', 'tone');
INSERT INTO public.tags VALUES (39, 'mythic', 'tone');
INSERT INTO public.tags VALUES (40, 'atmospheric', 'tone');
INSERT INTO public.tags VALUES (41, 'tense', 'tone');
INSERT INTO public.tags VALUES (42, 'hopeful', 'tone');
INSERT INTO public.tags VALUES (43, 'tragic', 'tone');
INSERT INTO public.tags VALUES (44, 'whimsical', 'tone');
INSERT INTO public.tags VALUES (45, 'chosen one', 'trope');
INSERT INTO public.tags VALUES (46, 'reluctant hero', 'trope');
INSERT INTO public.tags VALUES (47, 'assassin heroine', 'trope');
INSERT INTO public.tags VALUES (48, 'morally grey protagonist', 'trope');
INSERT INTO public.tags VALUES (49, 'powerful mentor', 'trope');
INSERT INTO public.tags VALUES (50, 'hidden identity', 'trope');
INSERT INTO public.tags VALUES (51, 'secret royalty', 'trope');
INSERT INTO public.tags VALUES (52, 'enemies to lovers', 'trope');
INSERT INTO public.tags VALUES (53, 'forbidden romance', 'trope');
INSERT INTO public.tags VALUES (54, 'found family fractures', 'trope');
INSERT INTO public.tags VALUES (55, 'magical training', 'trope');
INSERT INTO public.tags VALUES (56, 'ancient prophecy', 'trope');
INSERT INTO public.tags VALUES (57, 'quest narrative', 'trope');
INSERT INTO public.tags VALUES (58, 'court intrigue', 'trope');
INSERT INTO public.tags VALUES (59, 'tragic backstory', 'trope');

-- User Books
INSERT INTO public.user_books VALUES (1, 1, 1, 'read', 5.0, NULL, NULL, 'Wish she had more moments with the Prince');
INSERT INTO public.user_books VALUES (2, 1, 2, 'read', 5.0, NULL, NULL, NULL);
INSERT INTO public.user_books VALUES (3, 1, 3, 'read', 5.0, NULL, NULL, NULL);
INSERT INTO public.user_books VALUES (4, 1, 4, 'read', 5.0, NULL, NULL, NULL);
INSERT INTO public.user_books VALUES (5, 1, 5, 'read', 5.0, NULL, NULL, NULL);
INSERT INTO public.user_books VALUES (6, 1, 6, 'read', 4.0, NULL, NULL, NULL);
INSERT INTO public.user_books VALUES (7, 1, 7, 'read', 4.0, NULL, NULL, NULL);
INSERT INTO public.user_books VALUES (8, 1, 8, 'read', 5.0, NULL, NULL, NULL);

-- User Preferences
N/A

-- User
INSERT INTO public.users VALUES (1, 'Sabrina');